name: Deploy Storybook

on:
  push:
    branches:
      - 'main'

jobs:
  storybook-gh-pg:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.1

      - name: pnpm install
        run: pnpm i

      - name: Deploy Storybook to gh-page
        env:
          GH_TOKEN: ${{ github.actor }}:${{secrets.GITHUB_TOKEN}}
        run: pnpm deploy-storybook -- --ci
